# Identificação

**Nome:** Murilo Dias Oliveira  
**Matrícula:** 12402729  
**E-mail:** 12402729@aluno.cotemig.com.br

In [ ]:
!pip install numpy pandas openpyxl

In [2]:
import numpy as np
import pandas as pd

print("pandas:", pd.__version__)
print("numpy:", np.__version__)

pandas: 3.0.5
numpy: 2.5.3

In [9]:
caminho = r"H:\Python\3°Etapa\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

tabela = pd.read_excel(caminho, header = 2)

tabela

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
tabela_arrumada = tabela.iloc[0:5570, 1:]

tabela_arrumada

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0

In [15]:
tabela_arrumada["Diferença"] = tabela_arrumada["População 2010 (Alteração de limites até 2022)1"] - tabela_arrumada ["População do Censo 2022"]

tabela_arrumada

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Diferença
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,2898.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0,-6480.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0,962.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0,-8313.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0,1139.0
...,...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0,-2408.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,-1395.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0,520.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0,-670.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,-245222.0

In [16]:
tabela_arrumada.to_csv(r"H:\Python\3°Etapa\Tabela_Diferença.csv" , sep = ";")

In [18]:
tabela_estado =  (
    tabela_arrumada.groupby("UF")[["População de Censo 2022", "População do Município 2010\n(Sinopse)", "Diferença"]]

    .sum()
    .reset_index()
)

tabela_estado

    UF  População Censo 2022  População Município 2010\n(Sinopse)  Diferença
0   AC              830018.0                             733559.0   -96459.0
1   AL             3127683.0                            3120494.0    -6796.0
2   AM             3941613.0                            3483985.0  -457628.0
3   AP              733759.0                             669526.0   -64233.0
4   BA            14141626.0                           14016906.0  -124555.0
5   CE             8794957.0                            8452381.0  -343313.0
6   DF             2817381.0                            2570160.0  -245222.0
7   ES             3833712.0                            3514952.0  -318760.0
8   GO             7056495.0                            6003788.0 -1054706.0
9   MA             6776699.0                            6574789.0  -201910.0
10  MG            20539989.0                           19597330.0  -942659.0
11  MS             2757013.0                            2449024.0  -307989.0
12  MT             3658649.0                            3035122.0  -623527.0
13  PA             8120131.0                            7581051.0  -539080.0
14  PB             3974687.0                            3766528.0  -208159.0
15  PE             9058931.0                            8796448.0  -262876.0
16  PI             3271199.0                            3118360.0  -152102.0
17  PR            11444380.0                           10444526.0  -999854.0
18  RJ            16055174.0                           15989929.0   -65245.0
19  RN             3302729.0                            3168027.0  -134702.0
20  RO             1581196.0                            1562409.0   -18787.0
21  RR              636707.0                             450479.0  -186228.0
22  RS            10882965.0                           10693929.0  -189036.0
23  SC             7610361.0                            6248436.0 -1361925.0
24  SE             2210004.0                            2068017.0  -142152.0
25  SP            44411238.0                           41262199.0 -3149039.0
26  TO             1511460.0                            1383445.0  -128015.0

In [ ]:
tabela_municipio =  (
    tabela_arrumada.groupby("NOME DO MUNICÍPIO")[["População de Censo 2022", "População do Município 2010\n(Sinopse)", "Diferença"]]

    .sum()
    .reset_index()
)

tabela_estado